version: '3'
services:
  postgresql:
    image: postgres
    container_name: pg_docker
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=products_holder
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
